name: Create AMI

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Server IP address"
        required: true
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  create-ami:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip boto3

    - name: Extract instance ID
      id: get_instance_id
      run: |
        echo "Fetching instance ID for IP: ${{ github.event.inputs.server_ip }} in environment: ${{ github.event.inputs.environment }}..."
        # Replace with actual logic to fetch instance ID
        INSTANCE_ID="i-0abcdef1234567890"  # Placeholder instance ID
        if [ -z "$INSTANCE_ID" ]; then
          echo "Error: Instance ID could not be fetched."
          exit 1
        fi
        echo "::set-output name=instance_id::$INSTANCE_ID"
      shell: bash

    - name: Run Python Script to Create AMI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        python create_ami.py --instance-id ${{ steps.get_instance_id.outputs.instance_id }}
      continue-on-error: false  # Explicitly fail if the script returns a non-zero exit code
