name: Create AMI

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Server IP address"
        required: true
      environment:
        description: "Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  create-ami:
    runs-on: ubuntu-latest
    env:  # Define global environment variables for the job
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip boto3

    - name: Validate Server IP and Fetch Instance ID
      id: validate_ip
      run: |
        python create_ami.py --instance-ip ${{ github.event.inputs.server_ip }}
      shell: bash

    - name: Create AMI
      if: ${{ success() }}
      run: |
        # Replace this with the actual AMI creation logic
        echo "AMI creation process for validated instance."
